"""Synthetic per-class workload generation (DESIGN 5.1, traffic-math §2/§3).

:class:`SyntheticSource` implements the
:class:`~fleetsim.workload.base.JobSource` pull protocol: per workload
class it runs an independent arrival process (poisson | nhpp | mmpp2 |
hawkes — see ARRIVAL PROCESSES below), samples sizes/durations/tenants/
outcomes from named RNG streams, quantizes chip counts against the
fleet's node size, and merges all classes into one time-ordered stream
via a lazy heap.  Classes with ``arrival: backlog[target_pending=N]``
(v0.2) are CLOSED-LOOP instead: they emit nothing through
``next_arrival`` and are topped up to N pending jobs by the
engine-driven :meth:`SyntheticSource.refill` hook at every scheduler
wake — one source object covers both kinds.

UNITS: arrival times int microseconds since sim epoch; every ``*_s``
quantity float seconds.  Duration DistSpec params are **int microseconds**
(the config storage rule) — write them with unit suffixes
(``lognormal[median=2m, p90=30m]``); a bare number in a duration
expression is microseconds, NOT seconds.

ARRIVAL PROCESSES (traffic-math §2.1/§3; all draw only from the class's
``arrivals/<class>`` stream, in a pinned order):

- :class:`PoissonArrivals` — homogeneous; one exponential gap per event.
- :class:`NHPPArrivals` — Lewis-Shedler thinning against a rate curve
  (one exponential + one uniform per CANDIDATE); the curve is either the
  pinned v0.1 step curve (``seasonality: v01_steps`` — byte-identical to
  v0.1 ``diurnal: true``) or a log-linear harmonic
  :class:`HarmonicCurve` whose ``theta0`` normalization keeps the
  configured rate the mean.
- :class:`MMPP2Arrivals` — 2-state CTMC-modulated Poisson; per regime
  sojourn: one exponential (sojourn), one poisson (count), one
  ``uniform(size=n)`` (times), and — only with a seasonal envelope — one
  ``random(size=n)`` (thinning accepts).
- :class:`HawkesArrivals` — Ogata thinning with an exponential kernel
  (one exponential + one uniform per candidate); ``branching`` is the
  mean number of children per event (stationary iff < 1) and the NHPP
  baseline is derived as ``mu(t) = (1-branching) * lambda_c(t)``.

RNG STREAMS (the determinism contract; all derived from the shared
:class:`~fleetsim.engine.rng.RngStreams`):

- ``arrivals/<class>``: ALL arrival randomness, in the fixed per-process
  order above (gaps, thinning accepts, regime sojourns/counts, Hawkes
  accept draws).
- ``size/<class>``: one draw per job (chip count, pre-quantization).
- ``duration/<class>``: two draws per job — the true duration, then the
  walltime-overestimate factor (lognormal median 1.5, p90 3); THREE with
  a splice duration (branch + inversion + walltime factor).
- ``tenant/<class>``: one uniform per job (finite bounded Zipf over
  ``n_tenants`` with exponent ``tenant_zipf_s``, default 1.2 —
  traffic-math §2.4; tenants ``t0..t{n-1}``, ``t0`` dominant).
- ``outcome/<class>``: one uniform per job; jobs that abort
  (probability ``abort_prob``) draw two more — the FAILED(80%) /
  CANCELED(20%) split, then the early-truncation fraction ``U(0,1)^2``
  (failures skew early, DESIGN 5.1).

DIURNAL STEP CURVE (pinned, v0.1 compatible): multiplier 0.5 in
[00:00, 06:00), 0.8 in [12:00, 13:00) and [18:00, 19:00), else 1.0;
day = 86400 s.  Every curve is normalized so the configured rate is the
MEAN rate; arrivals are generated by thinning a homogeneous process at
the curve's peak-bound rate.

QUANTIZATION (DESIGN 4.1): a sampled size below the node size rounds UP
to the next power of two (becoming one whole node if that reaches the
node size); at/above the node size it rounds UP to a whole-node multiple.
Node size = max leaf chip count for the class's chip type (all leaves
when the fleet is heterogeneous and the type is unpinned).

INVARIANTS
----------
- Emitted ``(time_us, job)`` pairs are non-decreasing in time; times are
  strictly below the horizon; the source keeps returning ``None`` after
  exhaustion.
- Per class, draws happen in arrival order with the fixed per-stream
  counts above, so a run is a pure function of (config, fleet, seed).
- Jobs are plain declarative :class:`~fleetsim.model.Job` objects
  (:class:`SyntheticJob` adds only ``terminal_status_override``); one
  gang each, fresh ``Constraint`` per job (never shared with config).
"""

from __future__ import annotations

import heapq
import math
from bisect import bisect_right
from dataclasses import dataclass
from typing import Sequence

import numpy as np

from ..config import (
    HELIOS_V01_DAILY,
    ArrivalProcessConfig,
    SeasonalityConfig,
    WorkloadClassConfig,
    WorkloadConfig,
)
from ..engine.rng import RngStreams
from ..fleet.tree import FleetTree
from ..model import Constraint, GangSpec, Job, JobStatus
from ..units import DAY, HOUR
from .distributions import LogNormal, Sampler, from_spec

__all__ = [
    "SyntheticJob",
    "SyntheticSource",
    "diurnal_multiplier",
    "DIURNAL_MEAN",
    "quantize_chips",
    "node_sizes",
    "bounded_zipf_cdf",
    "StepCurve",
    "HarmonicCurve",
    "PoissonArrivals",
    "NHPPArrivals",
    "MMPP2Arrivals",
    "HawkesArrivals",
    "build_arrival_process",
]

#: Walltime-overestimate factor applied to the sampled true duration to
#: produce the scheduler-visible ``walltime_est_s`` (median 1.5x, p90 3x —
#: users overestimate; ~23% of draws are < 1, i.e. underestimates).
_WALLTIME_FACTOR = LogNormal(1.5, 3.0)

#: Mean of the pinned diurnal multiplier curve over one day
#: ((6h * 0.5 + 2h * 0.8 + 16h * 1.0) / 24h).
DIURNAL_MEAN = (6 * 0.5 + 2 * 0.8 + 16 * 1.0) / 24.0


def diurnal_multiplier(t_us: int) -> float:
    """The pinned diurnal rate multiplier at sim time ``t_us``.

    0.5 in [00:00, 06:00), 0.8 in [12:00, 13:00) and [18:00, 19:00),
    else 1.0 (night trough plus 12pm/6pm dips, per Helios).  The sim
    epoch is midnight.
    """
    hour = (t_us % DAY) / HOUR
    if hour < 6.0:
        return 0.5
    if 12.0 <= hour < 13.0 or 18.0 <= hour < 19.0:
        return 0.8
    return 1.0


def quantize_chips(raw: float, node_size: int, segment_nodes: int = 1) -> int:
    """Quantize a sampled chip count per DESIGN 4.1.

    ``raw`` is first ceiled to an int of at least 1.  Below ``node_size``
    it rounds UP to the next power of two (one whole node if that meets or
    exceeds the node size); at/above ``node_size`` it rounds UP to a
    whole-node multiple.  With ``segment_nodes > 1`` (segmented classes,
    v0.2) every draw instead rounds UP to a multiple of the SEGMENT
    quantum ``node_size * segment_nodes`` — segmented gangs are
    whole-node only and must divide into equal segments.  Raises
    ``ValueError`` on non-finite ``raw``, ``node_size < 1`` or
    ``segment_nodes < 1``.
    """
    if node_size < 1:
        raise ValueError(f"node_size must be >= 1, got {node_size}")
    if segment_nodes < 1:
        raise ValueError(f"segment_nodes must be >= 1, got {segment_nodes}")
    if not math.isfinite(raw):
        raise ValueError(f"sampled chip count must be finite, got {raw!r}")
    c = max(1, math.ceil(raw))
    if segment_nodes > 1:
        quantum = node_size * segment_nodes
        return quantum * -(-c // quantum)
    if c >= node_size:
        return node_size * -(-c // node_size)
    p = 1 << (c - 1).bit_length()  # next power of two >= c
    return p if p < node_size else node_size


def node_sizes(fleet: FleetTree) -> dict[str, int]:
    """Node size (max leaf chip count) per chip type, sorted by type.

    Raises ``ValueError`` if the fleet has no leaves.
    """
    out: dict[str, int] = {}
    for lid in fleet.leaves():
        leaf = fleet.domain(lid)
        out[leaf.chip_type] = max(out.get(leaf.chip_type, 0), leaf.chips)
    if not out:
        raise ValueError("fleet has no leaf nodes")
    return dict(sorted(out.items()))


def bounded_zipf_cdf(n: int, s: float) -> list[float]:
    """CDF of the FINITE Zipf pmf ``p_i ∝ (i+1)^-s`` over ranks
    ``0..n-1`` (traffic-math §2.4 — never ``rng.zipf``, which samples
    the unbounded Zeta distribution).  ``s == 0`` degenerates to
    uniform.  Returns ``n`` cumulative values with the last pinned to
    exactly 1.0.  Raises ``ValueError`` for ``n < 1`` or ``s < 0``.
    """
    if n < 1:
        raise ValueError(f"bounded_zipf_cdf requires n >= 1, got {n}")
    if s < 0:
        raise ValueError(f"bounded_zipf_cdf requires s >= 0, got {s}")
    weights = [(i + 1) ** -s for i in range(n)]
    total = sum(weights)
    cum: list[float] = []
    acc = 0.0
    for w in weights:
        acc += w / total
        cum.append(acc)
    cum[-1] = 1.0  # guard float accumulation
    return cum


# ---------------------------------------------------------------------------
# Rate curves (seasonality) and arrival processes — traffic-math §2.1/§3
# ---------------------------------------------------------------------------


class StepCurve:
    """The pinned v0.1 3-step diurnal curve as a thinning target.

    ``accept(t)`` is the raw multiplier (mean :data:`DIURNAL_MEAN` over
    a day); candidates run at the peak rate ``rate / DIURNAL_MEAN``.
    The candidate-gap expression is kept byte-identical to v0.1
    (``3600.0 * DIURNAL_MEAN / rate``) — part of the backward-compat
    contract for ``diurnal: true``.
    """

    __slots__ = ()

    #: Peak multiplier relative to the mean-normalized rate.
    vmax = 1.0 / DIURNAL_MEAN

    def candidate_gap_s(self, rate_per_hour: float) -> float:
        """Mean candidate gap in seconds at the thinning bound."""
        return 3600.0 * DIURNAL_MEAN / rate_per_hour

    def accept(self, t_us: int) -> float:
        """Thinning accept probability at ``t_us`` (in (0, 1])."""
        return diurnal_multiplier(t_us)

    def accept_array(self, ts_us: np.ndarray) -> np.ndarray:
        """Vectorized :meth:`accept` over an int-µs array."""
        hour = (ts_us % DAY) / HOUR
        out = np.ones(hour.shape, dtype=float)
        out[hour < 6.0] = 0.5
        out[((hour >= 12.0) & (hour < 13.0)) | ((hour >= 18.0) & (hour < 19.0))] = 0.8
        return out


class HarmonicCurve:
    """Log-linear harmonic rate curve (traffic-math §2.1).

    ``lambda(t) = rate * exp(theta0 + sum_k [a_k cos(2πkt/24h) + b_k
    sin(2πkt/24h)] + sum_k [A_k cos(2πkt/168h) + B_k sin(2πkt/168h)])``.
    The ``exp`` guarantees positivity (no clamping needed); ``theta0``
    is DERIVED here — weekly-mean normalization on a deterministic
    1-minute grid — so the configured rate stays the mean rate.  The
    exact thinning bound needs no grid:
    ``vmax = exp(theta0 + Σ√(a²+b²) + Σ√(A²+B²))``.

    INVARIANTS: pure function of the coefficient pairs; ≤3 daily and
    ≤2 weekly pairs (enforced by config validation); no randomness.
    """

    __slots__ = ("daily", "weekly", "theta0", "log_vmax", "vmax")

    def __init__(
        self,
        daily: tuple[tuple[float, float], ...],
        weekly: tuple[tuple[float, float], ...] = (),
    ):
        self.daily = tuple((float(a), float(b)) for a, b in daily)
        self.weekly = tuple((float(a), float(b)) for a, b in weekly)
        grid_h = np.arange(168 * 60, dtype=float) / 60.0  # 1-min grid, hours
        h = self._h_array(grid_h)
        self.theta0 = -float(np.log(np.mean(np.exp(h))))
        bound = sum(math.hypot(a, b) for a, b in self.daily) + sum(
            math.hypot(a, b) for a, b in self.weekly
        )
        self.log_vmax = self.theta0 + bound
        self.vmax = math.exp(self.log_vmax)

    def _h_array(self, t_h: np.ndarray) -> np.ndarray:
        h = np.zeros(t_h.shape, dtype=float)
        for k, (a, b) in enumerate(self.daily, start=1):
            w = 2.0 * math.pi * k / 24.0
            h += a * np.cos(w * t_h) + b * np.sin(w * t_h)
        for k, (a, b) in enumerate(self.weekly, start=1):
            w = 2.0 * math.pi * k / 168.0
            h += a * np.cos(w * t_h) + b * np.sin(w * t_h)
        return h

    def _h(self, t_h: float) -> float:
        h = 0.0
        for k, (a, b) in enumerate(self.daily, start=1):
            w = 2.0 * math.pi * k / 24.0
            h += a * math.cos(w * t_h) + b * math.sin(w * t_h)
        for k, (a, b) in enumerate(self.weekly, start=1):
            w = 2.0 * math.pi * k / 168.0
            h += a * math.cos(w * t_h) + b * math.sin(w * t_h)
        return h

    def multiplier(self, t_us: int) -> float:
        """Mean-1-normalized rate multiplier at ``t_us``."""
        return math.exp(self.theta0 + self._h(t_us / HOUR))

    def candidate_gap_s(self, rate_per_hour: float) -> float:
        """Mean candidate gap in seconds at the thinning bound."""
        return 3600.0 / (rate_per_hour * self.vmax)

    def accept(self, t_us: int) -> float:
        """Thinning accept probability ``lambda(t)/lambda_max``."""
        return math.exp(self.theta0 + self._h(t_us / HOUR) - self.log_vmax)

    def accept_array(self, ts_us: np.ndarray) -> np.ndarray:
        """Vectorized :meth:`accept` over an int-µs array."""
        return np.exp(
            self.theta0 + self._h_array(ts_us / HOUR) - self.log_vmax
        )


class PoissonArrivals:
    """Homogeneous Poisson: iid Exp gaps at the configured mean rate.

    Byte-identical to the v0.1 non-diurnal path (one
    ``rng.exponential`` per event, µs-rounded).
    """

    __slots__ = ("rate_per_hour",)

    def __init__(self, rate_per_hour: float):
        if rate_per_hour <= 0:
            raise ValueError(f"rate must be positive, got {rate_per_hour}")
        self.rate_per_hour = rate_per_hour

    def next_time(
        self, rng: np.random.Generator, prev_us: int, horizon_us: int
    ) -> int | None:
        gap_s = rng.exponential(3600.0 / self.rate_per_hour)
        t = prev_us + int(round(gap_s * 1e6))
        return t if t < horizon_us else None


class NHPPArrivals:
    """NHPP by Lewis-Shedler thinning against a rate curve.

    Candidates arrive at the curve's peak-bound rate; each candidate
    draws one exponential gap then one accept uniform (in that order,
    horizon-checked between — the pinned v0.1 draw order).  Rejected
    candidates advance time, so the loop always terminates.
    """

    __slots__ = ("rate_per_hour", "curve")

    def __init__(self, rate_per_hour: float, curve: StepCurve | HarmonicCurve):
        if rate_per_hour <= 0:
            raise ValueError(f"rate must be positive, got {rate_per_hour}")
        if curve is None:
            raise ValueError("NHPPArrivals requires a rate curve")
        self.rate_per_hour = rate_per_hour
        self.curve = curve

    def next_time(
        self, rng: np.random.Generator, prev_us: int, horizon_us: int
    ) -> int | None:
        mean_gap_s = self.curve.candidate_gap_s(self.rate_per_hour)
        t = prev_us
        while True:
            t += int(round(rng.exponential(mean_gap_s) * 1e6))
            if t >= horizon_us:
                return None
            if rng.random() < self.curve.accept(t):
                return t


class MMPP2Arrivals:
    """2-state Markov-modulated Poisson (traffic-math §2.1/§3.3).

    Hidden quiet/burst CTMC; config observables solve the four
    parameters in closed form: ``lambda_quiet = lambda_bar / (1 -
    burst_frac + burst_frac * rate_ratio)``, ``lambda_burst = rate_ratio
    * lambda_quiet``, ``sigma_qb = burst_frac / switch_tau``,
    ``sigma_bq = (1 - burst_frac) / switch_tau``.  With a seasonal
    envelope, base rates scale by the curve's ``vmax`` and every
    candidate is thinned by ``accept(t)`` so the configured rate stays
    the stationary mean.

    STATE: starts in quiet at t = 0 (pinned); regime sojourns are
    generated one at a time and each sojourn's arrivals are buffered
    (conditional uniformity), giving the fixed per-sojourn draw order:
    exponential (sojourn), poisson (count), uniform(size=n) (times),
    then random(size=n) envelope accepts (only when seasonal).
    """

    __slots__ = (
        "lam_q_s",
        "lam_b_s",
        "sig_qb",
        "sig_bq",
        "curve",
        "_state",
        "_t_s",
        "_buf",
        "_i",
    )

    def __init__(
        self,
        rate_per_hour: float,
        rate_ratio: float,
        burst_frac: float,
        switch_tau_s: float,
        curve: StepCurve | HarmonicCurve | None = None,
    ):
        if rate_per_hour <= 0:
            raise ValueError(f"rate must be positive, got {rate_per_hour}")
        if rate_ratio <= 1.0:
            raise ValueError(f"rate_ratio must be > 1, got {rate_ratio}")
        if not 0.0 < burst_frac < 1.0:
            raise ValueError(f"burst_frac must be in (0, 1), got {burst_frac}")
        if switch_tau_s <= 0:
            raise ValueError(f"switch_tau must be positive, got {switch_tau_s}")
        vmax = curve.vmax if curve is not None else 1.0
        lam_bar_s = rate_per_hour * vmax / 3600.0
        lam_q = lam_bar_s / (1.0 - burst_frac + burst_frac * rate_ratio)
        self.lam_q_s = lam_q
        self.lam_b_s = rate_ratio * lam_q
        self.sig_qb = burst_frac / switch_tau_s
        self.sig_bq = (1.0 - burst_frac) / switch_tau_s
        self.curve = curve
        self._state = 0  # 0 = quiet, 1 = burst
        self._t_s = 0.0
        self._buf: list[int] = []
        self._i = 0

    def next_time(
        self, rng: np.random.Generator, prev_us: int, horizon_us: int
    ) -> int | None:
        horizon_s = horizon_us * 1e-6
        while self._i >= len(self._buf):
            if self._t_s >= horizon_s:
                return None
            self._gen_sojourn(rng, horizon_s, horizon_us)
        t = self._buf[self._i]
        self._i += 1
        return t

    def _gen_sojourn(
        self, rng: np.random.Generator, horizon_s: float, horizon_us: int
    ) -> None:
        """Generate one regime sojourn's (thinned) arrivals into the
        buffer and flip the regime.  May produce zero arrivals."""
        rate, sw = (
            (self.lam_q_s, self.sig_qb)
            if self._state == 0
            else (self.lam_b_s, self.sig_bq)
        )
        start = self._t_s
        end = min(start + rng.exponential(1.0 / sw), horizon_s)
        n = int(rng.poisson(rate * (end - start)))
        self._buf = []
        self._i = 0
        if n:
            ts = np.sort(rng.uniform(start, end, n))
            ts_us = np.rint(ts * 1e6).astype(np.int64)
            if self.curve is not None:
                keep = rng.random(n) < self.curve.accept_array(ts_us)
                ts_us = ts_us[keep]
            self._buf = [int(x) for x in ts_us if x < horizon_us]
        self._t_s = end
        self._state = 1 - self._state


class HawkesArrivals:
    """Self-exciting Hawkes process by Ogata thinning (traffic-math
    §2.1/§3.2).

    Conditional intensity ``lambda(t) = mu(t) + sum_{t_i<t} alpha *
    exp(-beta (t - t_i))`` with ``alpha = branching * beta`` and
    ``beta = 1/kernel_tau``.  ``branching`` is the mean number of
    CHILDREN each event spawns — cluster sizes are Borel(branching) with
    mean ``1/(1-branching)``, so the process is stationary iff
    ``branching < 1`` (config validation enforces it).  The baseline is
    derived from the configured TOTAL mean rate: ``mu(t) =
    (1-branching) * rate * m(t)`` with ``m`` the (mean-1) seasonality
    multiplier — so the configured rate stays the stationary mean.

    STATE: the excitation sum ``A = Σ exp(-beta (t - t_i))`` decays in
    O(1) per candidate; one exponential + one uniform per candidate.
    """

    __slots__ = ("mu0_s", "mu_max_s", "alpha", "beta", "curve", "_A", "_t_us", "_done")

    def __init__(
        self,
        rate_per_hour: float,
        branching: float,
        kernel_tau_s: float,
        curve: StepCurve | HarmonicCurve | None = None,
    ):
        if rate_per_hour <= 0:
            raise ValueError(f"rate must be positive, got {rate_per_hour}")
        if not 0.0 <= branching < 1.0:
            raise ValueError(
                f"hawkes branching must be in [0, 1) for stationarity"
                f" (alpha/beta < 1), got {branching}"
            )
        if kernel_tau_s <= 0:
            raise ValueError(f"kernel_tau must be positive, got {kernel_tau_s}")
        rate_s = rate_per_hour / 3600.0
        vmax = curve.vmax if curve is not None else 1.0
        self.mu0_s = (1.0 - branching) * rate_s
        self.mu_max_s = self.mu0_s * vmax
        self.beta = 1.0 / kernel_tau_s
        self.alpha = branching * self.beta
        self.curve = curve
        self._A = 0.0
        self._t_us = 0
        self._done = False

    def next_time(
        self, rng: np.random.Generator, prev_us: int, horizon_us: int
    ) -> int | None:
        if self._done:
            return None
        t, a = self._t_us, self._A
        curve = self.curve
        while True:
            lam_bar = self.mu_max_s + self.alpha * a
            dt_us = int(round(rng.exponential(1.0 / lam_bar) * 1e6))
            if dt_us <= 0:
                dt_us = 1  # guarantee progress on sub-µs gaps
            t += dt_us
            a *= math.exp(-self.beta * (dt_us * 1e-6))
            if t >= horizon_us:
                self._t_us, self._A, self._done = t, a, True
                return None
            mu_t = (
                self.mu0_s * (curve.accept(t) * curve.vmax)
                if curve is not None
                else self.mu0_s
            )
            if rng.random() * lam_bar <= mu_t + self.alpha * a:
                a += 1.0  # the accepted event excites
                self._t_us, self._A = t, a
                return t


def _build_curve(
    seas: SeasonalityConfig | None,
) -> StepCurve | HarmonicCurve | None:
    """Build the rate curve for a parsed seasonality (None = flat)."""
    if seas is None:
        return None
    if seas.preset == "v01_steps":
        return StepCurve()
    if seas.preset == "helios_v01":
        return HarmonicCurve(HELIOS_V01_DAILY, ())
    if seas.preset is not None:
        raise ValueError(f"unknown seasonality preset {seas.preset!r}")
    return HarmonicCurve(seas.daily, seas.weekly)


def build_arrival_process(
    cfg: WorkloadClassConfig,
) -> PoissonArrivals | NHPPArrivals | MMPP2Arrivals | HawkesArrivals:
    """Build a class's arrival process from its parsed config.

    Dispatches on ``cfg.arrival_process`` (config parse always sets it
    for open-loop classes); a directly-constructed config without one
    falls back to the v0.1 fields (``diurnal`` -> nhpp on the step
    curve, else poisson).  Raises ``ValueError`` on unknown processes.
    """
    ap: ArrivalProcessConfig | None = cfg.arrival_process
    if ap is None:  # direct-construction fallback (v0.1 semantics)
        if cfg.diurnal:
            return NHPPArrivals(cfg.rate_per_hour, StepCurve())
        return PoissonArrivals(cfg.rate_per_hour)
    curve = _build_curve(ap.seasonality)
    if ap.process == "poisson":
        return PoissonArrivals(cfg.rate_per_hour)
    if ap.process == "nhpp":
        if curve is None:
            raise ValueError("arrival process 'nhpp' requires a seasonality")
        return NHPPArrivals(cfg.rate_per_hour, curve)
    if ap.process == "mmpp2":
        return MMPP2Arrivals(
            cfg.rate_per_hour,
            ap.mmpp2_rate_ratio,
            ap.mmpp2_burst_frac,
            ap.mmpp2_switch_tau_s,
            curve,
        )
    if ap.process == "hawkes":
        return HawkesArrivals(
            cfg.rate_per_hour,
            ap.hawkes_branching,
            ap.hawkes_kernel_tau_s,
            curve,
        )
    raise ValueError(f"unknown arrival process {ap.process!r}")


@dataclass(slots=True)
class SyntheticJob(Job):
    """A generated job; ``terminal_status_override`` (when set) is the
    terminal status the engine applies instead of COMPLETED when the job
    finishes its (possibly truncated) ``true_duration_s`` — how aborting
    jobs (DESIGN 5.1 outcomes) are represented."""

    terminal_status_override: JobStatus | None = None


class _ClassState:
    """Per-class generator state (streams, samplers, next candidate)."""

    __slots__ = (
        "cfg",
        "chip_sampler",
        "dur_sampler",
        "chip_type",
        "node_size",
        "process",
        "arrivals",
        "size",
        "duration",
        "tenant",
        "outcome",
        "tenant_cum",
        "n_emitted",
    )

    def __init__(
        self,
        cfg: WorkloadClassConfig,
        rng: RngStreams,
        chip_type: str | None,
        node_size: int,
    ):
        self.cfg = cfg
        self.chip_sampler: Sampler = from_spec(cfg.chips)
        self.dur_sampler: Sampler = from_spec(cfg.duration, scale=1e-6)
        self.chip_type = chip_type
        self.node_size = node_size
        # Backlog (closed-loop) classes have no arrival process; every
        # other class gets one built from its parsed config.
        is_backlog = cfg.arrival is not None and cfg.arrival.kind == "backlog"
        self.process = None if is_backlog else build_arrival_process(cfg)
        # Backlog (closed-loop) classes never draw from their arrivals
        # stream, but the stream is still created so its name stays
        # reserved either way (determinism contract).
        self.arrivals: np.random.Generator = rng.stream(f"arrivals/{cfg.name}")
        self.size: np.random.Generator = rng.stream(f"size/{cfg.name}")
        self.duration: np.random.Generator = rng.stream(f"duration/{cfg.name}")
        self.tenant: np.random.Generator = rng.stream(f"tenant/{cfg.name}")
        self.outcome: np.random.Generator = rng.stream(f"outcome/{cfg.name}")
        self.tenant_cum = bounded_zipf_cdf(cfg.n_tenants, cfg.tenant_zipf_s)
        self.n_emitted = 0


class SyntheticSource:
    """Merged multi-class synthetic :class:`~fleetsim.workload.base.JobSource`.

    Built from the parsed workload config, the runtime fleet tree (node
    sizes for quantization + chip-type pinning), the run's shared
    :class:`~fleetsim.engine.rng.RngStreams`, and the horizon.  Chip-type
    pinning (DESIGN §11: chips pinned per job): a class's configured
    ``chip_type`` wins; otherwise the fleet's sole chip type is pinned.
    On a heterogeneous fleet an unpinned class is a config error
    (``fleetsim.config.validate`` rejects it) and construction raises for
    a pinned type with no matching leaves.  Quantization uses the pinned
    type's node size (max leaf chips of that type).

    ``initial_jobs`` (e.g. the frozen inference replicas from
    :func:`fleetsim.workload.services.expand_services`) are merged into
    the stream at their own ``submit_t``; ties with sampled arrivals emit
    the initial job first.

    Raises ``ValueError`` at construction for a non-synthetic workload
    kind, classes with unknown job class / invalid distributions /
    non-positive rates, or multi-gang classes (not implemented in v0.1).
    """

    __slots__ = (
        "_horizon_us",
        "_states",
        "_heap",
        "_initial",
        "_initial_i",
        "_seq",
        "_backlog",
    )

    #: Heap class index used for ``initial_jobs`` (sorts before class 0).
    _INITIAL = -1

    def __init__(
        self,
        workload: WorkloadConfig,
        fleet: FleetTree,
        rng: RngStreams,
        horizon_us: int,
        *,
        initial_jobs: Sequence[Job] = (),
    ):
        if workload.kind != "synthetic":
            raise ValueError(
                f"SyntheticSource requires workload.kind 'synthetic',"
                f" got {workload.kind!r}"
            )
        if horizon_us <= 0:
            raise ValueError(f"horizon must be positive, got {horizon_us}")
        self._horizon_us = horizon_us

        sizes = node_sizes(fleet)
        sole_type = next(iter(sizes)) if len(sizes) == 1 else None
        default_node = max(sizes.values())

        self._states: list[_ClassState] = []
        # Closed-loop backlog classes (v0.2): (state, target_pending)
        # pairs in document order, driven by refill() instead of the
        # arrival heap.
        self._backlog: list[tuple[_ClassState, int]] = []
        # (time_us, class_index): ties resolve by index — initial jobs
        # (index -1) first, then classes in document order.
        self._heap: list[tuple[int, int]] = []
        for idx, cfg in enumerate(workload.classes):
            ctx = f"workload class {cfg.name!r}"
            if cfg.job_class is None:
                raise ValueError(f"{ctx}: unknown job class")
            backlog_target: int | None = None
            if cfg.arrival is not None:
                if cfg.arrival.kind != "backlog":
                    raise ValueError(
                        f"{ctx}: unknown arrival kind {cfg.arrival.kind!r}"
                        f" (known: backlog)"
                    )
                tp = cfg.arrival.params.get("target_pending")
                if not isinstance(tp, int) or isinstance(tp, bool) or tp < 1:
                    raise ValueError(
                        f"{ctx}: backlog requires an integer"
                        f" target_pending >= 1, got {tp!r}"
                    )
                backlog_target = tp
            elif cfg.rate_per_hour <= 0:
                raise ValueError(
                    f"{ctx}: arrival rate must be positive, got {cfg.rate_per_hour}"
                )
            if cfg.n_gangs != 1:
                raise ValueError(
                    f"{ctx}: multi-gang jobs are not implemented in v0.1"
                )
            pin = cfg.chip_type if cfg.chip_type is not None else sole_type
            if cfg.chip_type is not None and cfg.chip_type not in sizes:
                raise ValueError(
                    f"{ctx}: no fleet leaves of chip_type {cfg.chip_type!r}"
                    f" (present: {', '.join(sizes)})"
                )
            try:
                st = _ClassState(
                    cfg,
                    rng,
                    chip_type=pin,
                    node_size=sizes[pin] if pin is not None else default_node,
                )
            except ValueError as exc:
                raise ValueError(f"{ctx}: {exc}") from None
            self._states.append(st)
            if backlog_target is not None:
                self._backlog.append((st, backlog_target))
                continue  # closed-loop: no Poisson arrivals
            t = self._next_time(st, prev=0)
            if t is not None:
                heapq.heappush(self._heap, (t, idx))

        self._initial: list[Job] = sorted(
            initial_jobs, key=lambda j: (j.submit_t, j.id)
        )
        self._initial_i = 0
        if self._initial:
            heapq.heappush(
                self._heap, (self._initial[0].submit_t, self._INITIAL)
            )

    # -- arrival process -------------------------------------------------

    def _next_time(self, st: _ClassState, prev: int) -> int | None:
        """Next arrival time for a class after ``prev``, or ``None`` once
        past the horizon.  Delegates to the class's arrival process,
        which draws only from the ``arrivals/<class>`` stream."""
        return st.process.next_time(st.arrivals, prev, self._horizon_us)

    # -- job synthesis ---------------------------------------------------

    def _emit(self, st: _ClassState, t: int) -> Job:
        cfg = st.cfg
        chips = quantize_chips(
            st.chip_sampler.sample(st.size),
            st.node_size,
            cfg.segment_nodes if cfg.segment_nodes is not None else 1,
        )
        dur_s = st.dur_sampler.sample(st.duration)
        walltime_est_s = dur_s * _WALLTIME_FACTOR.sample(st.duration)
        if cfg.tenant is not None:
            # v0.4 fixed-tenant pin: no Zipf draw (the ``tenant/<class>``
            # stream stays reserved but unconsumed for this class).
            tenant = cfg.tenant
        else:
            tenant_i = min(
                bisect_right(st.tenant_cum, float(st.tenant.random())),
                cfg.n_tenants - 1,
            )
            tenant = f"t{tenant_i}"
        true_dur_s = dur_s
        override: JobStatus | None = None
        if st.outcome.random() < cfg.abort_prob:
            override = (
                JobStatus.FAILED
                if st.outcome.random() < 0.8
                else JobStatus.CANCELED
            )
            true_dur_s = dur_s * float(st.outcome.random()) ** 2
        within = (
            Constraint(
                level=cfg.within.level,
                required=cfg.within.required,
                relax_after_s=cfg.within.relax_after_s,
            )
            if cfg.within is not None
            else None
        )
        segments = (
            (cfg.segment_nodes, cfg.segment_level)
            if cfg.segment_nodes is not None and cfg.segment_level is not None
            else None
        )
        ckpt_on = cfg.checkpoint_interval_s and cfg.checkpoint_interval_s > 0
        job = SyntheticJob(
            id=f"{cfg.name}-{st.n_emitted}",
            tenant=tenant,
            job_class=cfg.job_class,
            submit_t=t,
            gangs=[
                GangSpec(
                    chips=chips,
                    chip_type=st.chip_type,
                    within=within,
                    segments=segments,
                    shape=cfg.shape,
                    twisted=cfg.twisted,
                )
            ],
            tier=cfg.tier,
            capacity=cfg.capacity,
            min_runtime_s=cfg.min_runtime_s,
            max_lifetime_s=cfg.max_lifetime_s,
            walltime_est_s=walltime_est_s,
            true_duration_s=true_dur_s,
            checkpoint_interval_s=cfg.checkpoint_interval_s,
            # No checkpoints -> nothing to save: preemption grace is 0 and
            # such victims are cheap kills (v0.2 best-effort semantics).
            checkpoint_save_s=60.0 if ckpt_on else 0.0,
            source_class=cfg.name,
            terminal_status_override=override,
        )
        st.n_emitted += 1
        return job

    # -- JobSource protocol ---------------------------------------------

    def refill(
        self, now_us: int, pending_by_class: dict[str, int]
    ) -> list[Job]:
        """Closed-loop backlog hook (v0.2): top every backlog class up to
        its ``target_pending`` pending jobs.

        Called by the engine at every SCHED_WAKE before the scheduler
        runs (see :class:`~fleetsim.workload.base.JobSource`).  A class's
        pending count is read from ``pending_by_class[cfg.name]`` (jobs
        carry ``source_class = cfg.name``).  Emitted jobs draw from the
        SAME per-class streams as Poisson classes (``size/<class>``,
        ``duration/<class>``, ``tenant/<class>``, ``outcome/<class>``) in
        deficit order — a pure function of (config, fleet, seed, call
        sequence).  Returns ``[]`` at or past the horizon.
        """
        if now_us >= self._horizon_us:
            return []
        jobs: list[Job] = []
        for st, target in self._backlog:  # document order
            deficit = target - pending_by_class.get(st.cfg.name, 0)
            for _ in range(deficit):
                jobs.append(self._emit(st, now_us))
        return jobs

    def next_arrival(self) -> tuple[int, Job] | None:
        """The next ``(time_us, job)`` in merged time order, or ``None``
        once every class is past the horizon (and stays ``None``)."""
        if not self._heap:
            return None
        t, idx = heapq.heappop(self._heap)
        if idx == self._INITIAL:
            job = self._initial[self._initial_i]
            self._initial_i += 1
            if self._initial_i < len(self._initial):
                heapq.heappush(
                    self._heap,
                    (self._initial[self._initial_i].submit_t, self._INITIAL),
                )
            return (t, job)
        st = self._states[idx]
        job = self._emit(st, t)
        nxt = self._next_time(st, prev=t)
        if nxt is not None:
            heapq.heappush(self._heap, (nxt, idx))
        return (t, job)
