"""Synthetic per-class workload generation (DESIGN 5.1).

:class:`SyntheticSource` implements the
:class:`~fleetsim.workload.base.JobSource` pull protocol: per workload
class it runs an independent (optionally diurnally-thinned) Poisson
arrival process, samples sizes/durations/tenants/outcomes from named RNG
streams, quantizes chip counts against the fleet's node size, and merges
all classes into one time-ordered stream via a lazy heap.

UNITS: arrival times int microseconds since sim epoch; every ``*_s``
quantity float seconds.  Duration DistSpec params are **int microseconds**
(the config storage rule) — write them with unit suffixes
(``lognormal[median=2m, p90=30m]``); a bare number in a duration
expression is microseconds, NOT seconds.

RNG STREAMS (the determinism contract; all derived from the shared
:class:`~fleetsim.engine.rng.RngStreams`):

- ``arrivals/<class>``: inter-arrival gaps; when ``diurnal`` also the
  thinning accept draws (one uniform per candidate).
- ``size/<class>``: one draw per job (chip count, pre-quantization).
- ``duration/<class>``: two draws per job — the true duration, then the
  walltime-overestimate factor (lognormal median 1.5, p90 3).
- ``tenant/<class>``: one uniform per job (zipf-ish tenant pick,
  exponent 1.5, tenants ``t0..t{n-1}``, ``t0`` dominant).
- ``outcome/<class>``: one uniform per job; jobs that abort
  (probability ``abort_prob``) draw two more — the FAILED(80%) /
  CANCELED(20%) split, then the early-truncation fraction ``U(0,1)^2``
  (failures skew early, DESIGN 5.1).

DIURNAL CURVE (pinned): multiplier 0.5 in [00:00, 06:00), 0.8 in
[12:00, 13:00) and [18:00, 19:00), else 1.0; day = 86400 s.  The curve is
normalized so the configured rate is the MEAN rate over a day; arrivals
are generated by thinning a homogeneous process at the peak rate.

QUANTIZATION (DESIGN 4.1): a sampled size below the node size rounds UP
to the next power of two (becoming one whole node if that reaches the
node size); at/above the node size it rounds UP to a whole-node multiple.
Node size = max leaf chip count for the class's chip type (all leaves
when the fleet is heterogeneous and the type is unpinned).

INVARIANTS
----------
- Emitted ``(time_us, job)`` pairs are non-decreasing in time; times are
  strictly below the horizon; the source keeps returning ``None`` after
  exhaustion.
- Per class, draws happen in arrival order with the fixed per-stream
  counts above, so a run is a pure function of (config, fleet, seed).
- Jobs are plain declarative :class:`~fleetsim.model.Job` objects
  (:class:`SyntheticJob` adds only ``terminal_status_override``); one
  gang each, fresh ``Constraint`` per job (never shared with config).
"""

from __future__ import annotations

import heapq
import math
from bisect import bisect_right
from dataclasses import dataclass
from typing import Sequence

import numpy as np

from ..config import WorkloadClassConfig, WorkloadConfig
from ..engine.rng import RngStreams
from ..fleet.tree import FleetTree
from ..model import Constraint, GangSpec, Job, JobStatus
from ..units import DAY, HOUR
from .distributions import LogNormal, Sampler, from_spec

__all__ = [
    "SyntheticJob",
    "SyntheticSource",
    "diurnal_multiplier",
    "DIURNAL_MEAN",
    "quantize_chips",
    "node_sizes",
]

#: Walltime-overestimate factor applied to the sampled true duration to
#: produce the scheduler-visible ``walltime_est_s`` (median 1.5x, p90 3x —
#: users overestimate; ~23% of draws are < 1, i.e. underestimates).
_WALLTIME_FACTOR = LogNormal(1.5, 3.0)

#: Zipf exponent for the tenant skew (weights ``(i+1) ** -1.5``).
_TENANT_ZIPF_S = 1.5

#: Mean of the pinned diurnal multiplier curve over one day
#: ((6h * 0.5 + 2h * 0.8 + 16h * 1.0) / 24h).
DIURNAL_MEAN = (6 * 0.5 + 2 * 0.8 + 16 * 1.0) / 24.0


def diurnal_multiplier(t_us: int) -> float:
    """The pinned diurnal rate multiplier at sim time ``t_us``.

    0.5 in [00:00, 06:00), 0.8 in [12:00, 13:00) and [18:00, 19:00),
    else 1.0 (night trough plus 12pm/6pm dips, per Helios).  The sim
    epoch is midnight.
    """
    hour = (t_us % DAY) / HOUR
    if hour < 6.0:
        return 0.5
    if 12.0 <= hour < 13.0 or 18.0 <= hour < 19.0:
        return 0.8
    return 1.0


def quantize_chips(raw: float, node_size: int) -> int:
    """Quantize a sampled chip count per DESIGN 4.1.

    ``raw`` is first ceiled to an int of at least 1.  Below ``node_size``
    it rounds UP to the next power of two (one whole node if that meets or
    exceeds the node size); at/above ``node_size`` it rounds UP to a
    whole-node multiple.  Raises ``ValueError`` on non-finite ``raw`` or
    ``node_size < 1``.
    """
    if node_size < 1:
        raise ValueError(f"node_size must be >= 1, got {node_size}")
    if not math.isfinite(raw):
        raise ValueError(f"sampled chip count must be finite, got {raw!r}")
    c = max(1, math.ceil(raw))
    if c >= node_size:
        return node_size * -(-c // node_size)
    p = 1 << (c - 1).bit_length()  # next power of two >= c
    return p if p < node_size else node_size


def node_sizes(fleet: FleetTree) -> dict[str, int]:
    """Node size (max leaf chip count) per chip type, sorted by type.

    Raises ``ValueError`` if the fleet has no leaves.
    """
    out: dict[str, int] = {}
    for lid in fleet.leaves():
        leaf = fleet.domain(lid)
        out[leaf.chip_type] = max(out.get(leaf.chip_type, 0), leaf.chips)
    if not out:
        raise ValueError("fleet has no leaf nodes")
    return dict(sorted(out.items()))


@dataclass(slots=True)
class SyntheticJob(Job):
    """A generated job; ``terminal_status_override`` (when set) is the
    terminal status the engine applies instead of COMPLETED when the job
    finishes its (possibly truncated) ``true_duration_s`` — how aborting
    jobs (DESIGN 5.1 outcomes) are represented."""

    terminal_status_override: JobStatus | None = None


class _ClassState:
    """Per-class generator state (streams, samplers, next candidate)."""

    __slots__ = (
        "cfg",
        "chip_sampler",
        "dur_sampler",
        "chip_type",
        "node_size",
        "arrivals",
        "size",
        "duration",
        "tenant",
        "outcome",
        "tenant_cum",
        "n_emitted",
    )

    def __init__(
        self,
        cfg: WorkloadClassConfig,
        rng: RngStreams,
        chip_type: str | None,
        node_size: int,
    ):
        self.cfg = cfg
        self.chip_sampler: Sampler = from_spec(cfg.chips)
        self.dur_sampler: Sampler = from_spec(cfg.duration, scale=1e-6)
        self.chip_type = chip_type
        self.node_size = node_size
        self.arrivals: np.random.Generator = rng.stream(f"arrivals/{cfg.name}")
        self.size: np.random.Generator = rng.stream(f"size/{cfg.name}")
        self.duration: np.random.Generator = rng.stream(f"duration/{cfg.name}")
        self.tenant: np.random.Generator = rng.stream(f"tenant/{cfg.name}")
        self.outcome: np.random.Generator = rng.stream(f"outcome/{cfg.name}")
        weights = [(i + 1) ** -_TENANT_ZIPF_S for i in range(cfg.n_tenants)]
        total = sum(weights)
        cum: list[float] = []
        acc = 0.0
        for w in weights:
            acc += w / total
            cum.append(acc)
        cum[-1] = 1.0  # guard float accumulation
        self.tenant_cum = cum
        self.n_emitted = 0


class SyntheticSource:
    """Merged multi-class synthetic :class:`~fleetsim.workload.base.JobSource`.

    Built from the parsed workload config, the runtime fleet tree (node
    sizes for quantization + chip-type pinning), the run's shared
    :class:`~fleetsim.engine.rng.RngStreams`, and the horizon.  Chip-type
    pinning (DESIGN §11: chips pinned per job): a class's configured
    ``chip_type`` wins; otherwise the fleet's sole chip type is pinned.
    On a heterogeneous fleet an unpinned class is a config error
    (``fleetsim.config.validate`` rejects it) and construction raises for
    a pinned type with no matching leaves.  Quantization uses the pinned
    type's node size (max leaf chips of that type).

    ``initial_jobs`` (e.g. the frozen inference replicas from
    :func:`fleetsim.workload.services.expand_services`) are merged into
    the stream at their own ``submit_t``; ties with sampled arrivals emit
    the initial job first.

    Raises ``ValueError`` at construction for a non-synthetic workload
    kind, classes with unknown job class / invalid distributions /
    non-positive rates, or multi-gang classes (not implemented in v0.1).
    """

    __slots__ = ("_horizon_us", "_states", "_heap", "_initial", "_initial_i", "_seq")

    #: Heap class index used for ``initial_jobs`` (sorts before class 0).
    _INITIAL = -1

    def __init__(
        self,
        workload: WorkloadConfig,
        fleet: FleetTree,
        rng: RngStreams,
        horizon_us: int,
        *,
        initial_jobs: Sequence[Job] = (),
    ):
        if workload.kind != "synthetic":
            raise ValueError(
                f"SyntheticSource requires workload.kind 'synthetic',"
                f" got {workload.kind!r}"
            )
        if horizon_us <= 0:
            raise ValueError(f"horizon must be positive, got {horizon_us}")
        self._horizon_us = horizon_us

        sizes = node_sizes(fleet)
        sole_type = next(iter(sizes)) if len(sizes) == 1 else None
        default_node = max(sizes.values())

        self._states: list[_ClassState] = []
        # (time_us, class_index): ties resolve by index — initial jobs
        # (index -1) first, then classes in document order.
        self._heap: list[tuple[int, int]] = []
        for idx, cfg in enumerate(workload.classes):
            ctx = f"workload class {cfg.name!r}"
            if cfg.job_class is None:
                raise ValueError(f"{ctx}: unknown job class")
            if cfg.rate_per_hour <= 0:
                raise ValueError(
                    f"{ctx}: arrival rate must be positive, got {cfg.rate_per_hour}"
                )
            if cfg.n_gangs != 1:
                raise ValueError(
                    f"{ctx}: multi-gang jobs are not implemented in v0.1"
                )
            pin = cfg.chip_type if cfg.chip_type is not None else sole_type
            if cfg.chip_type is not None and cfg.chip_type not in sizes:
                raise ValueError(
                    f"{ctx}: no fleet leaves of chip_type {cfg.chip_type!r}"
                    f" (present: {', '.join(sizes)})"
                )
            try:
                st = _ClassState(
                    cfg,
                    rng,
                    chip_type=pin,
                    node_size=sizes[pin] if pin is not None else default_node,
                )
            except ValueError as exc:
                raise ValueError(f"{ctx}: {exc}") from None
            self._states.append(st)
            t = self._next_time(st, prev=0)
            if t is not None:
                heapq.heappush(self._heap, (t, idx))

        self._initial: list[Job] = sorted(
            initial_jobs, key=lambda j: (j.submit_t, j.id)
        )
        self._initial_i = 0
        if self._initial:
            heapq.heappush(
                self._heap, (self._initial[0].submit_t, self._INITIAL)
            )

    # -- arrival process -------------------------------------------------

    def _next_time(self, st: _ClassState, prev: int) -> int | None:
        """Next arrival time for a class after ``prev``, or ``None`` once
        past the horizon (rejected thinning candidates advance time, so
        the loop always terminates)."""
        cfg = st.cfg
        if not cfg.diurnal:
            gap_s = st.arrivals.exponential(3600.0 / cfg.rate_per_hour)
            t = prev + int(round(gap_s * 1e6))
            return t if t < self._horizon_us else None
        # Thinning against the pinned curve: candidates at the peak rate
        # (multiplier 1.0), normalized so the configured rate is the mean.
        mean_gap_s = 3600.0 * DIURNAL_MEAN / cfg.rate_per_hour
        t = prev
        while True:
            t += int(round(st.arrivals.exponential(mean_gap_s) * 1e6))
            if t >= self._horizon_us:
                return None
            if st.arrivals.random() < diurnal_multiplier(t):
                return t

    # -- job synthesis ---------------------------------------------------

    def _emit(self, st: _ClassState, t: int) -> Job:
        cfg = st.cfg
        chips = quantize_chips(st.chip_sampler.sample(st.size), st.node_size)
        dur_s = st.dur_sampler.sample(st.duration)
        walltime_est_s = dur_s * _WALLTIME_FACTOR.sample(st.duration)
        tenant_i = min(
            bisect_right(st.tenant_cum, float(st.tenant.random())),
            cfg.n_tenants - 1,
        )
        true_dur_s = dur_s
        override: JobStatus | None = None
        if st.outcome.random() < cfg.abort_prob:
            override = (
                JobStatus.FAILED
                if st.outcome.random() < 0.8
                else JobStatus.CANCELED
            )
            true_dur_s = dur_s * float(st.outcome.random()) ** 2
        within = (
            Constraint(
                level=cfg.within.level,
                required=cfg.within.required,
                relax_after_s=cfg.within.relax_after_s,
            )
            if cfg.within is not None
            else None
        )
        job = SyntheticJob(
            id=f"{cfg.name}-{st.n_emitted}",
            tenant=f"t{tenant_i}",
            job_class=cfg.job_class,
            submit_t=t,
            gangs=[
                GangSpec(
                    chips=chips,
                    chip_type=st.chip_type,
                    within=within,
                    shape=cfg.shape,
                    twisted=cfg.twisted,
                )
            ],
            tier=cfg.tier,
            capacity=cfg.capacity,
            min_runtime_s=cfg.min_runtime_s,
            max_lifetime_s=cfg.max_lifetime_s,
            walltime_est_s=walltime_est_s,
            true_duration_s=true_dur_s,
            checkpoint_interval_s=cfg.checkpoint_interval_s,
            terminal_status_override=override,
        )
        st.n_emitted += 1
        return job

    # -- JobSource protocol ---------------------------------------------

    def next_arrival(self) -> tuple[int, Job] | None:
        """The next ``(time_us, job)`` in merged time order, or ``None``
        once every class is past the horizon (and stays ``None``)."""
        if not self._heap:
            return None
        t, idx = heapq.heappop(self._heap)
        if idx == self._INITIAL:
            job = self._initial[self._initial_i]
            self._initial_i += 1
            if self._initial_i < len(self._initial):
                heapq.heappush(
                    self._heap,
                    (self._initial[self._initial_i].submit_t, self._INITIAL),
                )
            return (t, job)
        st = self._states[idx]
        job = self._emit(st, t)
        nxt = self._next_time(st, prev=t)
        if nxt is not None:
            heapq.heappush(self._heap, (nxt, idx))
        return (t, job)
